export const desktopChannels = {
  bootstrapState: "desktop:get-bootstrap-state",
  openExternal: "desktop:open-external",
  themeChanged: "desktop:theme-changed",
  getWindowHotkeyState: "desktop:hotkey-window:get-state",
  setWindowHotkey: "desktop:hotkey-window:set-hotkey",
  clearWindowHotkey: "desktop:hotkey-window:clear-hotkey",
  getSnapshot: "desktop:data:get-snapshot",
  createThread: "desktop:data:create-thread",
  appendMessage: "desktop:data:append-message",
  selectThread: "desktop:data:select-thread",
  selectAutomation: "desktop:data:select-automation",
  togglePluginConnection: "desktop:data:toggle-plugin-connection",
  updateAutomation: "desktop:data:update-automation",
  updateAutomationSchedule: "desktop:data:update-automation-schedule",
  updateSettings: "desktop:data:update-settings",
  addBrowserDomain: "desktop:data:add-browser-domain",
  removeBrowserDomain: "desktop:data:remove-browser-domain",
  showApplicationMenu: "desktop:show-application-menu",
} as const;
